import { Topic } from './topic';

import { faUserGroup, faScrewdriverWrench, faHouse, faTag, faSuitcase, faHandshake, faFile } from '@fortawesome/free-solid-svg-icons';

export const TOPICS: Topic[] = [
  {
    id: 1, 
    name: 'community', 
    icon: faUserGroup,
    categories: [
      'activities', 
      'artists', 
      'childcare',
      'classes',
      'events', 
      'general',
      'groups',
      'local news',
      'lost+found', 
      'missed',
      'connections',
      'musicians',
      'pets', 
      'politics', 
      'rants & raves', 
      'rideshare', 
      'volunteers']
  },
  { id: 2, 
    name: 'services', 
    icon: faScrewdriverWrench, 
    categories: [
      'automotive',
      'beauty',
      'cell/mobile',
      'computer',
      'creative',
      'cycle',
      'event',
      'farm+garden',
      'financial',
      'health/well',
      'household',
      'labor/move',
      'legal',
      'lessons',
      'marine',
      'pet',
      'real estate',
      'skilled trade',
      'small biz ads',
      'travel/vac',
      'write/ed/tran'
    ]
  },
  { id: 3, 
    name: 'housing', 
    icon: faHouse,
    categories: [
      'apts/housing',
      'housing swap',
      'housing wanted',
      'office/commercial',
      'parking/storage',
      'real estate for sale',
      'rooms/shared',
      'rooms wanted',
      'sublets/temporary',
      'vacation rentals'
    ]
  },
  { id: 4, 
    name: 'for sale', 
    icon: faTag,
    categories: [
      'antiques',
      'appliances',
      'arts+crafts',
      'atv/utv/sno',
      'auto parts',
      'baby+kids',
      'barter',
      'beauty+hlth',
      'bikes',
      'boats',
      'books',
      'business',
      'cars+trucks',
      'cds/dvd/vhs',
      'cell phones',
      'clothes+acc',
      'collectibles',
      'computer parts',
      'computers',
      'electronics',
      'farm+garden',
      'free',
      'furniture',
      'garage sale',
      'general',
      'heavy equip',
      'household',
      'jewelry',
      'materials',
      'motorcycles',
      'music instr',
      'photo+video',
      'rvs+camp',
      'sporting',
      'tickets',
      'tools',
      'toys+games',
      'trailers',
      'video gaming',
      'wanted',
      'auto wheels & tires',
    ]
  },
  { id: 5, 
    name: 'jobs', 
    icon: faSuitcase,
    categories: [
      'accounting+finance',
      'admin/office',
      'arch/engineering',
      'art/media/design',
      'biotech/science',
      'business/mgmt',
      'customer service',
      'education',
      'food/bev/hosp',
      'general labor',
      'government',
      'human resources',
      'legal/paralegal',
      'manufacturing',
      'marketing/advertising/pr',
      'nonprofit',
      'real estate',
      'retail/wholesale',
      'sales',
      'salon/spa/fitness',
      'security',
      'skilled trades/artisan',
      'software/qa/dba/etc',
      'systems/networking',
      'technical support',
      'transport',
      'tv/film/video',
      'web/info design',
      'writing/editing',
    ]
  },
  { id: 6, 
    name: 'gigs', 
    icon: faHandshake,
    categories: [
      'computer',
      'creative',
      'crew',
      'domestic',
      'event',
      'labor',
      'talent',
      'writing'
    ]
  },

];